version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-app
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:xG/vMrKjM75ZJi1/HQfvrgtOjEMnwYsAtkJ98sIa2w4=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel-net

networks:
  laravel-net:

volumes:
  dbdata:
